---
# defaults file for docker
default_conf: /etc/default/docker
docker_service_file: /usr/lib/systemd/system/docker.service
docker_storage: /data/docker/data
docker_reg_mirror: http://e617eb29.m.daocloud.io
#docker_reg_mirror: https://registry.htres.cn 
docker_port: 2376
firewall_enable: false
