apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: logstash
    spec:
      containers:
      - name: logstash
        image: logstash:5.6
        imagePullPolicy: Always
        command:
        - logstash
        args:
        - -f
        - /data/logstash-conf
        volumeMounts:
        - name: logstash-consumer-config
          mountPath: /data/logstash-conf
      volumes:
          - configMap:
              name: logstash-consumer-config
            name: logstash-consumer-config
