registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
    REGISTRY_HTTP_TLS_KEY: /certs/registry.key
  volumes:
    - /data/registry:/var/lib/registry
    - /data/app/registry/certs:/certs
    - /data/app/registry/config.yml:/etc/docker/registry/config.yml
