---
- name: Add kubernetes repo
  copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
      backup: yes
- name: Install kubelet
  yum: name={{item}} state=latest
  with_items:
    - kubelet
    - kubeadm
    - kubectl
- name: copy kubeadm template
  template: src=templates/10-kubeadm.conf.j2 dest="/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
- name: reload kubelet service config
  command: "systemctl daemon-reload"
- name: enable kubelet
  service: name=kubelet enabled=yes
- name: Restart kubelet
  service: name=kubelet state=restarted
